name: prova
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.NEVIERE_TOKEN }}
on:
  commit:
    branches:
      - development
