name: Build and deploy Neviere di Sicilia Jekyll site to GitHub Pages

on:
  push:
    branches:
      - development

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.NEVIERE_TOKEN }}
